# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app1.ui'
#
# Created: Fri Oct  3 11:48:32 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(974, 622)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 62, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_Init = QtGui.QPushButton(Form)
        self.pushButton_Init.setGeometry(QtCore.QRect(160, 20, 71, 61))
        self.pushButton_Init.setObjectName(_fromUtf8("pushButton_Init"))
        self.comboBox_Port = QtGui.QComboBox(Form)
        self.comboBox_Port.setGeometry(QtCore.QRect(20, 40, 131, 26))
        self.comboBox_Port.setEditable(True)
        self.comboBox_Port.setObjectName(_fromUtf8("comboBox_Port"))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Port.addItem(_fromUtf8(""))
        self.comboBox_Baud = QtGui.QComboBox(Form)
        self.comboBox_Baud.setGeometry(QtCore.QRect(20, 100, 131, 26))
        self.comboBox_Baud.setEditable(True)
        self.comboBox_Baud.setObjectName(_fromUtf8("comboBox_Baud"))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.comboBox_Baud.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_Stop = QtGui.QPushButton(Form)
        self.pushButton_Stop.setGeometry(QtCore.QRect(160, 80, 71, 61))
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(250, 10, 711, 591))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.graph_Speed = PlotWidget(self.tab)
        self.graph_Speed.setGeometry(QtCore.QRect(10, 0, 691, 551))
        self.graph_Speed.setObjectName(_fromUtf8("graph_Speed"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.graph_Deplace = PlotWidget(self.tab_2)
        self.graph_Deplace.setGeometry(QtCore.QRect(10, 0, 691, 551))
        self.graph_Deplace.setObjectName(_fromUtf8("graph_Deplace"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.graph_Current = PlotWidget(self.tab_3)
        self.graph_Current.setGeometry(QtCore.QRect(10, 0, 691, 551))
        self.graph_Current.setObjectName(_fromUtf8("graph_Current"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 480, 211, 119))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.text_Information = QtGui.QTextEdit(self.groupBox_3)
        self.text_Information.setGeometry(QtCore.QRect(0, 20, 211, 101))
        self.text_Information.setObjectName(_fromUtf8("text_Information"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(20, 600, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 140, 211, 331))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 150, 201, 139))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalSlider_cP = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_cP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_cP.setMouseTracking(True)
        self.horizontalSlider_cP.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cP.setObjectName(_fromUtf8("horizontalSlider_cP"))
        self.gridLayout_2.addWidget(self.horizontalSlider_cP, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.horizontalSlider_cI = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_cI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_cI.setMouseTracking(True)
        self.horizontalSlider_cI.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cI.setObjectName(_fromUtf8("horizontalSlider_cI"))
        self.gridLayout_2.addWidget(self.horizontalSlider_cI, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.horizontalSlider_cD = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_cD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_cD.setMouseTracking(True)
        self.horizontalSlider_cD.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_cD.setObjectName(_fromUtf8("horizontalSlider_cD"))
        self.gridLayout_2.addWidget(self.horizontalSlider_cD, 2, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_2.addWidget(self.spinBox_4, 0, 2, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_2.addWidget(self.spinBox_5, 1, 2, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_2.addWidget(self.spinBox_6, 2, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 201, 139))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalSlider_sP = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_sP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_sP.setMouseTracking(True)
        self.horizontalSlider_sP.setAutoFillBackground(False)
        self.horizontalSlider_sP.setTracking(True)
        self.horizontalSlider_sP.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sP.setObjectName(_fromUtf8("horizontalSlider_sP"))
        self.gridLayout.addWidget(self.horizontalSlider_sP, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalSlider_sI = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_sI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_sI.setMouseTracking(True)
        self.horizontalSlider_sI.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sI.setObjectName(_fromUtf8("horizontalSlider_sI"))
        self.gridLayout.addWidget(self.horizontalSlider_sI, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.horizontalSlider_sD = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_sD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_sD.setMouseTracking(True)
        self.horizontalSlider_sD.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sD.setObjectName(_fromUtf8("horizontalSlider_sD"))
        self.gridLayout.addWidget(self.horizontalSlider_sD, 2, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 0, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout.addWidget(self.spinBox_2, 1, 2, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout.addWidget(self.spinBox_3, 2, 2, 1, 1)
        self.pushButton_Send = QtGui.QPushButton(self.frame)
        self.pushButton_Send.setGeometry(QtCore.QRect(130, 290, 71, 41))
        self.pushButton_Send.setObjectName(_fromUtf8("pushButton_Send"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 63, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.horizontalSlider_sP, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox.setValue)
        QtCore.QObject.connect(self.horizontalSlider_sI, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.horizontalSlider_sD, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_sP.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_sI.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_sD.setValue)
        QtCore.QObject.connect(self.horizontalSlider_cP, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_4.setValue)
        QtCore.QObject.connect(self.horizontalSlider_cI, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_5.setValue)
        QtCore.QObject.connect(self.horizontalSlider_cD, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_6.setValue)
        QtCore.QObject.connect(self.spinBox_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_cP.setValue)
        QtCore.QObject.connect(self.spinBox_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_cI.setValue)
        QtCore.QObject.connect(self.spinBox_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_cD.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "串口/Port", None))
        self.pushButton_Init.setText(_translate("Form", "Init", None))
        self.comboBox_Port.setItemText(0, _translate("Form", "/dev/ttyACM0", None))
        self.comboBox_Port.setItemText(1, _translate("Form", "/dev/ttyACM1", None))
        self.comboBox_Port.setItemText(2, _translate("Form", "/dev/ttyACM2", None))
        self.comboBox_Port.setItemText(3, _translate("Form", "/dev/ttyACM3", None))
        self.comboBox_Port.setItemText(4, _translate("Form", "/dev/ttyACM4", None))
        self.comboBox_Port.setItemText(5, _translate("Form", "/dev/ttyACM5", None))
        self.comboBox_Port.setItemText(6, _translate("Form", "/dev/ttyACM6", None))
        self.comboBox_Baud.setItemText(0, _translate("Form", "115200", None))
        self.comboBox_Baud.setItemText(1, _translate("Form", "57600", None))
        self.comboBox_Baud.setItemText(2, _translate("Form", "38400", None))
        self.comboBox_Baud.setItemText(3, _translate("Form", "28800", None))
        self.comboBox_Baud.setItemText(4, _translate("Form", "19200", None))
        self.comboBox_Baud.setItemText(5, _translate("Form", "14400", None))
        self.comboBox_Baud.setItemText(6, _translate("Form", "9600", None))
        self.comboBox_Baud.setItemText(7, _translate("Form", "4800", None))
        self.label_2.setText(_translate("Form", "带宽/Daud", None))
        self.pushButton_Stop.setText(_translate("Form", "Stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "速度/  Speed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "位移/Deplace", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "电流/Current", None))
        self.groupBox_3.setTitle(_translate("Form", "提示/Information", None))
        self.label_9.setText(_translate("Form", "Author: LIU Zhichao", None))
        self.groupBox_2.setTitle(_translate("Form", "电流反馈/Current Control", None))
        self.label_6.setText(_translate("Form", "P", None))
        self.label_7.setText(_translate("Form", "I", None))
        self.label_8.setText(_translate("Form", "D", None))
        self.groupBox.setTitle(_translate("Form", "速度反馈/Speed Control", None))
        self.label_3.setText(_translate("Form", "P", None))
        self.label_4.setText(_translate("Form", "I", None))
        self.label_5.setText(_translate("Form", "D", None))
        self.pushButton_Send.setText(_translate("Form", "Start", None))
        self.label_10.setText(_translate("Form", "开始/Start", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

